import { CharacterClass, MiscFeatureId } from "../../types/characterClasses";
import { CharacterSheetData } from "../../types/characterSheetData";
import { MovementType, Size } from "../../types/misc";
import { Proficiency, Skill } from "../../types/skills";
import { Stat, StatArray } from "../../types/stats";
import { generateCharacterAtEachLevelV1, LevelBonus } from "./characterBuilder";

// Barbarian
const exampleLevelBonuses: LevelBonus[] = [
  {
    characterClass: CharacterClass.FIGHTER,
    hp: 12,
    skillProfs: [
      { skill: Skill.ATHLETICS, proficiency: Proficiency.EXPERTISE },
      { skill: Skill.INTIMIDATION, proficiency: Proficiency.PROFICIENT },
    ],
  },
  { characterClass: CharacterClass.FIGHTER, hp: 7 },
  { characterClass: CharacterClass.FIGHTER, hp: 7 },
  {
    characterClass: CharacterClass.FIGHTER,
    hp: 7,
    asis: [Stat.STR, Stat.CON],
  },
];

const exampleBaseStatArray: StatArray = {
  [Stat.STR]: 10,
  [Stat.DEX]: 14,
  [Stat.CON]: 18,
  [Stat.INT]: 10,
  [Stat.WIS]: 10,
  [Stat.CHA]: 10,
};

export const exampleCalculatedCharacter = generateCharacterAtEachLevelV1(
  "Placeholder name",
  exampleBaseStatArray,
  exampleLevelBonuses,
);

const basicFighterBaseStatArray: StatArray = {
  [Stat.STR]: 10,
  [Stat.DEX]: 10,
  [Stat.CON]: 10,
  [Stat.INT]: 10,
  [Stat.WIS]: 10,
  [Stat.CHA]: 10,
};

export const basicFighter = generateCharacterAtEachLevelV1(
  "Placeholder name",
  basicFighterBaseStatArray,
  [{ hp: 10, characterClass: CharacterClass.FIGHTER }],
);

export const placeholderCharacterSheetData: CharacterSheetData = {
  name: "Placeholder Name",
  alignment: "Neutral good",
  species: "Human",
  size: Size.MEDIUM,
  background: "Soldier",
  classLevels: [],
  armorClass: 10,
  movement: [{ mode: MovementType.WALK, amount: 30 }],
  maxHp: 0,
  hitDice: [],
  proficiencyBonus: 0,
  stats: {
    [Stat.STR]: 10,
    [Stat.DEX]: 10,
    [Stat.CON]: 10,
    [Stat.INT]: 10,
    [Stat.WIS]: 10,
    [Stat.CHA]: 10,
  },
  statMods: {
    [Stat.STR]: 0,
    [Stat.DEX]: 0,
    [Stat.CON]: 0,
    [Stat.INT]: 0,
    [Stat.WIS]: 0,
    [Stat.CHA]: 0,
  },
  saveProficiencies: {
    [Stat.STR]: false,
    [Stat.DEX]: false,
    [Stat.CON]: false,
    [Stat.INT]: false,
    [Stat.WIS]: false,
    [Stat.CHA]: false,
  },
  saveBonuses: {
    [Stat.STR]: 0,
    [Stat.DEX]: 0,
    [Stat.CON]: 0,
    [Stat.INT]: 0,
    [Stat.WIS]: 0,
    [Stat.CHA]: 0,
  },
  skillProficiencies: {
    [Skill.ATHLETICS]: Proficiency.NOT_PROFICIENT,
    [Skill.ACROBATICS]: Proficiency.NOT_PROFICIENT,
    [Skill.SLEIGHT_OF_HAND]: Proficiency.NOT_PROFICIENT,
    [Skill.STEALTH]: Proficiency.NOT_PROFICIENT,
    [Skill.ARCANA]: Proficiency.NOT_PROFICIENT,
    [Skill.HISTORY]: Proficiency.NOT_PROFICIENT,
    [Skill.INVESTIGATION]: Proficiency.NOT_PROFICIENT,
    [Skill.NATURE]: Proficiency.NOT_PROFICIENT,
    [Skill.RELIGION]: Proficiency.NOT_PROFICIENT,
    [Skill.ANIMAL_HANDLING]: Proficiency.NOT_PROFICIENT,
    [Skill.INSIGHT]: Proficiency.NOT_PROFICIENT,
    [Skill.MEDICINE]: Proficiency.NOT_PROFICIENT,
    [Skill.PERCEPTION]: Proficiency.NOT_PROFICIENT,
    [Skill.SURVIVAL]: Proficiency.NOT_PROFICIENT,
    [Skill.DECEPTION]: Proficiency.NOT_PROFICIENT,
    [Skill.INTIMIDATION]: Proficiency.NOT_PROFICIENT,
    [Skill.PERFORMANCE]: Proficiency.NOT_PROFICIENT,
    [Skill.PERSUASION]: Proficiency.NOT_PROFICIENT,
  },
  skillBonuses: {
    [Skill.ATHLETICS]: 0,
    [Skill.ACROBATICS]: 0,
    [Skill.SLEIGHT_OF_HAND]: 0,
    [Skill.STEALTH]: 0,
    [Skill.ARCANA]: 0,
    [Skill.HISTORY]: 0,
    [Skill.INVESTIGATION]: 0,
    [Skill.NATURE]: 0,
    [Skill.RELIGION]: 0,
    [Skill.ANIMAL_HANDLING]: 0,
    [Skill.INSIGHT]: 0,
    [Skill.MEDICINE]: 0,
    [Skill.PERCEPTION]: 0,
    [Skill.SURVIVAL]: 0,
    [Skill.DECEPTION]: 0,
    [Skill.INTIMIDATION]: 0,
    [Skill.PERFORMANCE]: 0,
    [Skill.PERSUASION]: 0,
  },
  miscProficiencies: [],
  features: [],
  spells: undefined,
  attacks: undefined,
  equipment: undefined,
};

export const exampleCharacterSheetData: CharacterSheetData = {
  name: "John Example",
  alignment: "Neutral good",
  species: "Human",
  size: Size.MEDIUM,
  background: "Soldier",
  classLevels: [
    { characterClass: CharacterClass.FIGHTER, level: 2 },
    { characterClass: CharacterClass.ROGUE, level: 1 },
  ],
  armorClass: 15,
  movement: [{ mode: MovementType.WALK, amount: 30 }],
  maxHp: 27,
  hitDice: [
    { size: 10, number: 2 },
    { size: 8, number: 1 },
  ],
  proficiencyBonus: 2,
  stats: {
    [Stat.STR]: 16,
    [Stat.DEX]: 15,
    [Stat.CON]: 14,
    [Stat.INT]: 13,
    [Stat.WIS]: 11,
    [Stat.CHA]: 9,
  },
  statMods: {
    [Stat.STR]: 3,
    [Stat.DEX]: 2,
    [Stat.CON]: 2,
    [Stat.INT]: 1,
    [Stat.WIS]: 0,
    [Stat.CHA]: -1,
  },
  saveProficiencies: {
    [Stat.STR]: true,
    [Stat.DEX]: false,
    [Stat.CON]: true,
    [Stat.INT]: false,
    [Stat.WIS]: false,
    [Stat.CHA]: false,
  },
  saveBonuses: {
    [Stat.STR]: 5,
    [Stat.DEX]: 2,
    [Stat.CON]: 4,
    [Stat.INT]: 1,
    [Stat.WIS]: 0,
    [Stat.CHA]: -1,
  },
  skillProficiencies: {
    [Skill.ATHLETICS]: Proficiency.EXPERTISE,
    [Skill.ACROBATICS]: Proficiency.EXPERTISE,
    [Skill.SLEIGHT_OF_HAND]: Proficiency.PROFICIENT,
    [Skill.STEALTH]: Proficiency.NOT_PROFICIENT,
    [Skill.ARCANA]: Proficiency.NOT_PROFICIENT,
    [Skill.HISTORY]: Proficiency.PROFICIENT,
    [Skill.INVESTIGATION]: Proficiency.NOT_PROFICIENT,
    [Skill.NATURE]: Proficiency.NOT_PROFICIENT,
    [Skill.RELIGION]: Proficiency.NOT_PROFICIENT,
    [Skill.ANIMAL_HANDLING]: Proficiency.PROFICIENT,
    [Skill.INSIGHT]: Proficiency.NOT_PROFICIENT,
    [Skill.MEDICINE]: Proficiency.NOT_PROFICIENT,
    [Skill.PERCEPTION]: Proficiency.NOT_PROFICIENT,
    [Skill.SURVIVAL]: Proficiency.NOT_PROFICIENT,
    [Skill.DECEPTION]: Proficiency.NOT_PROFICIENT,
    [Skill.INTIMIDATION]: Proficiency.NOT_PROFICIENT,
    [Skill.PERFORMANCE]: Proficiency.NOT_PROFICIENT,
    [Skill.PERSUASION]: Proficiency.NOT_PROFICIENT,
  },
  skillBonuses: {
    [Skill.ATHLETICS]: 7,
    [Skill.ACROBATICS]: 6,
    [Skill.SLEIGHT_OF_HAND]: 4,
    [Skill.STEALTH]: 2,
    [Skill.ARCANA]: 1,
    [Skill.HISTORY]: 3,
    [Skill.INVESTIGATION]: 1,
    [Skill.NATURE]: 1,
    [Skill.RELIGION]: 1,
    [Skill.ANIMAL_HANDLING]: 2,
    [Skill.INSIGHT]: 0,
    [Skill.MEDICINE]: 0,
    [Skill.PERCEPTION]: 0,
    [Skill.SURVIVAL]: 0,
    [Skill.DECEPTION]: -1,
    [Skill.INTIMIDATION]: -1,
    [Skill.PERFORMANCE]: -1,
    [Skill.PERSUASION]: -1,
  },
  miscProficiencies: [
    {
      name: "All armor",
      proficiency: Proficiency.PROFICIENT,
    },
    {
      name: "Shields",
      proficiency: Proficiency.PROFICIENT,
    },
    {
      name: "Simple weapons",
      proficiency: Proficiency.PROFICIENT,
    },
    {
      name: "Martial weapons",
      proficiency: Proficiency.PROFICIENT,
    },
    {
      name: "Thieves' tools",
      proficiency: Proficiency.PROFICIENT,
    },
  ],
  features: [
    MiscFeatureId.FIGHTING_STYLE,
    MiscFeatureId.SECOND_WIND,
    `${MiscFeatureId.ACTION_SURGE} (x1)`,
    `${MiscFeatureId.SNEAK_ATTACK} (1d6)`,
    MiscFeatureId.THIEVES_CANT,
  ],
  spells: undefined,
  attacks: undefined,
  equipment: undefined,
};
